# Generated by Django 4.0.5 on 2022-06-28 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webFundacionApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Residentes',
            new_name='Residente',
        ),
    ]
