# Generated by Django 4.0.5 on 2022-06-28 04:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webFundacionApp', '0002_rename_residentes_residente'),
    ]

    operations = [
        migrations.AddField(
            model_name='residente',
            name='contacto',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residente',
            name='enfermedades',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residente',
            name='observaciones',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
