# Generated by Django 4.0.4 on 2022-06-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webFundacionApp', '0003_residente_contacto_residente_enfermedades_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('residencia', models.CharField(max_length=50)),
                ('monto', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
        ),
    ]
