# Generated by Django 4.0.4 on 2022-06-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webFundacionApp', '0004_aporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aporte',
            name='fecha',
            field=models.CharField(max_length=50),
        ),
    ]
